from __future__ import annotations

import csv
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts/generate_fulfillment_classification_seed.py"
OUTPUT = ROOT / "supabase/sql/024_profit_fulfillment_classification_seed_20260504.sql"
AUDIT_CSV = ROOT / "docs/audits/2026-05-04-fulfillment-leaks-classification.csv"


class FulfillmentClassificationSeedTests(unittest.TestCase):
    def test_generator_source_contains_canon_and_normalization_rules(self) -> None:
        source = SCRIPT.read_text(encoding="utf-8")

        self.assertIn("CANONICAL_VERDICTS", source)
        self.assertIn("CONSOLIDATED_VIA_GROUP_BILLED", source)
        self.assertIn("consolidated_via_group_billed", source)
        self.assertIn("strip()", source)
        self.assertIn("Unknown verdict", source)
        self.assertIn("PENDING_ENGAGEMENT_DRAFT", source)
        self.assertIn("PENDING_ENGAGEMENT_SENT", source)
        self.assertIn(
            "Audit CSV captured this row as PENDING_ENGAGEMENT_* on 2026-05-04",
            source,
        )

    def test_audit_csv_verdicts_normalize_to_14_canon(self) -> None:
        canon = {
            "INTERNAL_FAMILY",
            "INACTIVE_FORMER_CLIENT",
            "PENDING_ENGAGEMENT_DRAFT",
            "PENDING_ENGAGEMENT_SENT",
            "INVOICE_OUTSTANDING_PAYMENT_PENDING",
            "LEGACY_ENGAGEMENT_PRE_ANCHOR",
            "ENGAGEMENT_DECLINED",
            "LEGITIMATE_LEAK",
            "BILLING_OUTSIDE_AUDIT_WINDOW",
            "BILLING_SETUP_GAP",
            "GROUP_DEFINITION_GAP",
            "MIXED",
            "CONSOLIDATED_VIA_GROUP_BILLED",
            "SETTLED_VIA_QUICKBOOKS_PAYMENT",
        }
        aliases = {"consolidated_via_group_billed": "CONSOLIDATED_VIA_GROUP_BILLED"}

        with AUDIT_CSV.open(newline="", encoding="utf-8") as handle:
            reader = csv.DictReader(handle)
            normalized = []
            for row in reader:
                raw = row["veredict"]
                value = aliases.get(raw.strip(), raw.strip().upper())
                normalized.append(value)

        self.assertTrue(normalized)
        self.assertEqual(set(normalized) - canon, set())

    def test_generated_seed_sql_shape_is_idempotent_and_traceable(self) -> None:
        sql = OUTPUT.read_text(encoding="utf-8")
        lower = sql.lower()

        self.assertIn(
            "generated by scripts/generate_fulfillment_classification_seed.py",
            lower,
        )
        self.assertIn(
            "source audit file: docs/audits/2026-05-04-fulfillment-leaks-classification.csv",
            lower,
        )
        self.assertIn("rows seeded as captured:", lower)
        self.assertIn("rows reclassified to mixed due to drift:", lower)
        self.assertIn("insert into profit_classifications", lower)
        self.assertIn(
            "on conflict (source_audit_file, source_audit_row_hash) do update set",
            lower,
        )
        self.assertIn("source_audit_row_hash", lower)
        self.assertIn("source_verdict_raw", lower)
        self.assertIn("estimated_annual_revenue", lower)
        self.assertIn("re_evaluate_at", lower)


if __name__ == "__main__":
    unittest.main()
