-- Generated by scripts/generate_service_crosswalk_seed.py.
-- Source files:
--   docs/data-references/anchor services.csv
--   docs/data-references/qbo-product-services.csv

alter table profit_service_recognition_rules
  add column if not exists fc_tag text,
  add column if not exists qbo_category_path text,
  add column if not exists qbo_product_name text;

create index if not exists idx_profit_service_recognition_rules_fc_tag
  on profit_service_recognition_rules (fc_tag)
  where fc_tag is not null;

create index if not exists idx_profit_service_recognition_rules_qbo_product
  on profit_service_recognition_rules (qbo_product_name)
  where qbo_product_name is not null;

insert into profit_service_recognition_rules (
  service_name,
  macro_service_type,
  service_tier,
  recognition_pattern,
  service_period_rule,
  default_sla_day,
  form_type_pattern,
  notes,
  fc_tag,
  qbo_category_path,
  qbo_product_name,
  source,
  last_synced_at
) values
  ('1040 Advanced', 'tax', 'Advanced', 'tax_filing', 'tax_year_default', null, '1040', 'Tier is complexity, not timing.', 'S 1040A', 'Tax Work', '1040 Advanced', 'manual_seed', now()),
  ('1040 Essentials', 'tax', 'Essentials', 'tax_filing', 'tax_year_default', null, '1040', 'Tier is complexity, not timing.', 'S 1040E', 'Tax Work', '1040 Essentials', 'manual_seed', now()),
  ('1040 Plus', 'tax', 'Plus', 'tax_filing', 'tax_year_default', null, '1040', 'Tier is complexity, not timing.', 'S 1040P', 'Tax Work', '1040 Plus', 'manual_seed', now()),
  ('1065 Advanced', 'tax', 'Advanced', 'tax_filing', 'tax_year_default', null, '1065', 'Tier is complexity, not timing.', 'S 1065A', 'Tax Work', '1065 Advanced', 'manual_seed', now()),
  ('1065 Essential', 'tax', 'Essential', 'tax_filing', 'tax_year_default', null, '1065', 'Tier is complexity, not timing.', 'S 1065E', 'Tax Work', '1065 Essential', 'manual_seed', now()),
  ('1065 Plus', 'tax', 'Plus', 'tax_filing', 'tax_year_default', null, '1065', 'Tier is complexity, not timing.', 'S 1065P', 'Tax Work', '1065 Plus', 'manual_seed', now()),
  ('1099 Preparation', 'tax', null, 'manual_review', 'manual', null, null, 'Monthly $0 edge case; require explicit review before automation.', 'S 1099', 'Tax Work', '1099 Preparation', 'manual_seed', now()),
  ('1120 Advanced', 'tax', 'Advanced', 'tax_filing', 'tax_year_default', null, '1120', 'Matches 1120 and 1120S corporate returns.', 'S 1120A', 'Tax Work', '1120 Advanced', 'manual_seed', now()),
  ('1120 Essential', 'tax', 'Essential', 'tax_filing', 'tax_year_default', null, '1120', 'Matches 1120 and 1120S corporate returns.', 'S 1120E', 'Tax Work', '1120 Essential', 'manual_seed', now()),
  ('1120 Plus', 'tax', 'Plus', 'tax_filing', 'tax_year_default', null, '1120', 'Matches 1120 and 1120S corporate returns.', 'S 1120P', 'Tax Work', '1120 Plus', 'manual_seed', now()),
  ('990 Full Return Essential', 'tax', 'Essential', 'tax_filing', 'tax_year_default', null, '990', 'Nonprofit full return.', 'S 990E', 'Tax Work', '990 Full Return Essential', 'manual_seed', now()),
  ('990 Full Return Plus', 'tax', 'Plus', 'tax_filing', 'tax_year_default', null, '990', 'Nonprofit full return.', 'S 990P', 'Tax Work', '990 Full Return Plus', 'manual_seed', now()),
  ('990-EZ Short Form', 'tax', 'Short Form', 'tax_filing', 'tax_year_default', null, '990-EZ', 'Nonprofit short form.', 'S 990EZ', 'Tax Work', '990-EZ Short Form', 'manual_seed', now()),
  ('990-T Unrelated Business', 'tax', null, 'tax_filing', 'tax_year_default', null, '990-T', 'Unrelated business income return.', 'S 990T', 'Tax Work', '990-T Unrelated Business', 'manual_seed', now()),
  ('Accounting Advanced', 'bookkeeping', 'Advanced', 'monthly_recurring', 'previous_month', 10, null, 'Per-engagement SLA override allowed via profit_anchor_agreements.sla_day_override.', 'S BOOKA', 'Accounting', 'Accounting Advanced', 'manual_seed', now()),
  ('Accounting Essential', 'bookkeeping', 'Essential', 'monthly_recurring', 'previous_month', 20, null, 'Recognize from FC bookkeeping completion for prior month.', 'S BOOKE', 'Accounting', 'Accounting Essential', 'manual_seed', now()),
  ('Accounting Plus', 'bookkeeping', 'Plus', 'monthly_recurring', 'previous_month', 10, null, 'Recognize from FC bookkeeping completion for prior month.', 'S BOOKP', 'Accounting', 'Accounting Plus', 'manual_seed', now()),
  ('Advisory', 'advisory', null, 'one_time', 'invoice_date', null, null, 'Hourly project/ad-hoc advisory.', 'S ADV', 'Advisory', 'Advisory', 'manual_seed', now()),
  ('Annual Estimate Tax Review', 'tax', null, 'one_time', 'invoice_date', null, 'estimate review', 'Recognize when estimate review is delivered/completed.', 'S ETP', 'Tax Work', 'Annual Estimate Tax Review', 'manual_seed', now()),
  ('Audit Protection Business', 'other', 'Business', 'manual_review', 'manual', null, null, 'Insurance-style accrual; enum does not yet include insurance_accrual. Review before automated recognition.', 'S AUDITB', 'Tax Work', 'Audit Protection Business', 'manual_seed', now()),
  ('Audit Protection Individual', 'other', 'Individual', 'manual_review', 'manual', null, null, 'Insurance-style accrual; enum does not yet include insurance_accrual. Review before automated recognition.', 'S AUDITI', 'Tax Work', 'Audit Protection Individual', 'manual_seed', now()),
  ('Audit Support Service', 'advisory', null, 'one_time', 'invoice_date', null, null, 'Audit support is work performed, not audit protection.', 'S AUDITS', 'Other', 'Audit Support Service', 'manual_seed', now()),
  ('Billable Expenses', 'pass_through', null, 'pass_through', 'manual', null, null, 'Exclude from service revenue recognition.', 'S BILL', 'Other', 'Billable Expenses', 'manual_seed', now()),
  ('Fractional CFO', 'advisory', null, 'monthly_recurring', 'previous_month', null, null, 'Recognize on advisory delivery/monthly meeting cadence.', 'S CFO', 'Advisory', 'Fractional CFO', 'manual_seed', now()),
  ('Other Income', 'pass_through', null, 'pass_through', 'manual', null, null, 'Exclude from service recognition unless separately reviewed.', null, 'Other', 'Other Income', 'manual_seed', now()),
  ('Payroll Service', 'payroll', null, 'monthly_recurring', 'previous_month', null, null, 'SLA follows payroll cadence; recognize by payroll processed trigger.', 'S PAYROLL', 'Payroll', 'Payroll Service', 'manual_seed', now()),
  ('Payroll Tax Compliance', 'payroll', null, 'quarterly_recurring', 'previous_quarter', null, null, 'Quarterly federal/state deadline-driven SLA.', 'S PAYTAX', 'Payroll', 'Payroll Tax Compliance', 'manual_seed', now()),
  ('Remote Desktop Access', 'pass_through', null, 'pass_through', 'manual', null, null, 'Client reimbursement/access cost recovery.', 'S BILL', 'Other', 'Remote Desktop Access', 'manual_seed', now()),
  ('Remote QBD Access', 'pass_through', null, 'pass_through', 'manual', null, null, 'Client reimbursement/access cost recovery.', 'S BILL', 'Other', 'Remote QBD Access', 'manual_seed', now()),
  ('Sales Tax Compliance', 'sales_tax', null, 'monthly_recurring', 'previous_month', 20, null, 'Sales tax compliance is not annual income tax; keep out of tax_filed matching.', 'S SALESTAX', 'Tax Work', 'Sales Tax Compliance', 'manual_seed', now()),
  ('Services', 'pass_through', null, 'pass_through', 'manual', null, null, 'Generic product excluded by default; explicit classification required.', null, 'Advisory', 'Services', 'manual_seed', now()),
  ('Setup and Onboarding', 'advisory', null, 'one_time', 'invoice_date', null, null, 'Recognize at onboarding delivery/completion.', 'S SETUP', 'Advisory', 'Setup and Onboarding', 'manual_seed', now()),
  ('Specialized Services', 'advisory', null, 'manual_review', 'manual', null, null, 'Default $0/varies; review before automated recognition.', null, 'Other', 'Specialized Services', 'manual_seed', now()),
  ('Tangible Property Tax', 'tax', null, 'manual_review', 'manual', null, null, 'Monthly billing exists but annual tangible-property cadence requires review.', 'S TPP', 'Tax Work', 'Tangible Property Tax', 'manual_seed', now()),
  ('Work Comp Tax', 'payroll', null, 'manual_review', 'manual', null, null, 'Workers comp/payroll-adjacent compliance; review before automation.', 'S WORKERS', 'Payroll', 'Work Comp Tax', 'manual_seed', now()),
  ('Year End Accounting Close', 'bookkeeping', null, 'manual_review', 'manual', null, null, 'Default $0/varies; review before automated recognition.', 'S YECLOSE', 'Accounting', 'Year End Accounting Close', 'manual_seed', now())
on conflict (service_name) do update set
  macro_service_type = excluded.macro_service_type,
  service_tier = excluded.service_tier,
  recognition_pattern = excluded.recognition_pattern,
  service_period_rule = excluded.service_period_rule,
  default_sla_day = excluded.default_sla_day,
  form_type_pattern = excluded.form_type_pattern,
  notes = excluded.notes,
  fc_tag = excluded.fc_tag,
  qbo_category_path = excluded.qbo_category_path,
  qbo_product_name = excluded.qbo_product_name,
  source = excluded.source,
  last_synced_at = now(),
  updated_at = now();

create or replace view profit_anchor_services_without_tag as
select
  rule.service_name,
  rule.macro_service_type,
  rule.recognition_pattern,
  rule.service_period_rule,
  rule.qbo_category_path,
  rule.qbo_product_name,
  rule.last_synced_at
from profit_service_recognition_rules rule
where rule.fc_tag is null
  and rule.macro_service_type <> 'pass_through'
order by rule.service_name;
